### ISSUE TITLE
make ST3 compatible

### ISSUE THREAD

**Issue by jcartledge** [jcartledge/sublime-worksheet#15]
yeah ok

**Comment by jcartledge** [comment]
not sure if there is a Py3 pexpect?

**Comment by sindresorhus** [comment]
:+1:

**Comment by n1k0** [comment]
:+1:

**Comment by skippednote** [comment]
:+1:

**Comment by gAmUssA** [comment]
Yes, please :+1:

**Comment by jcartledge** [comment]
I'm sensing a theme here.

**Comment by pahen** [comment]
:+1:

**Comment by olistik** [comment]
:+1:

**Comment by alpacaaa** [comment]
:+1: ^ :100:

**Comment by jcartledge** [comment]
That was quick! @timonwong has supplied a patch for ST3 compatibility at #24. Can anyone who is interested check out his fork and test it? Please update that thread if it works (or doesn't) for you.

**Comment by olistik** [comment]
@jcartledge it works for me, I've tested it against some ruby code.

**Comment by jcartledge** [comment]
This is in master now. I'll wrap it up into a release in the next day or so.
