### ISSUE TITLE
Code doesn't executes if there's no new line after statement

### ISSUE THREAD

**Issue by rrader** [jcartledge/sublime-worksheet#26]
Steps to reproduce:

Using this code:

```
for x in range(2):
    print (x)
print("END")
```

Result:

```
for x in range(2):
    print (x)
print("END")
# >   File "<stdin>", line 3
# >     print("END")
# >         ^
# > SyntaxError: invalid syntax
```

Expected result:

```
for x in range(2):
    print (x)
# > 0
# > 1
print("END")
# > END
```

**Comment by jcartledge** [comment]
This is a limitation of the Python interpreter - if you try your example in the interpreter you'll get the same error.
I am going to merge your PR as it fixes #27, but it doesn't fix this. 

I just need to ensure your patch doesn't cause (or reveal) problems in other languages. Thanks!
