### ISSUE TITLE
Sublime 3 Support

### ISSUE THREAD

**Issue by cjmcqueen** [jcartledge/sublime-worksheet#33]
Installed on Sublime 3 without error, but Worksheet: Eval doesn't appear in the the command palette.

**Comment by jcartledge** [comment]
Hi Chris,

How did you install the plugin? ST3 support isn't in package control yet, but if you grabbed it from GitHub then it should work.

**Comment by cjmcqueen** [comment]
I used package control to install. I'll uninstall and try git. Thanks!

**Comment by jcartledge** [comment]
I've just pushed 0.8.0 which supports ST2 and 3 (thanks to @timonwong) - it should be in Package Control soon.
