### ISSUE TITLE
Using Boris as a PHP REPL alternative.

### ISSUE THREAD

**Issue by WMeldon** [jcartledge/sublime-worksheet#39]
I was playing around with this and wanted to use [Boris](https://github.com/d11wtq/boris) instead.  After a couple small explosions to figure out how the settings worked, I found this to work when added to the user settings: 

```
"worksheet_languages": {
    "PHP": {
        "cmd": "/path/to/boris",
        "prompt": ["(\\[[\\d]+\\]) (boris> | *\\*>)"],
        "error": ["PHP Parse error:", "PHP Fatal error"],
        "ignore": ["<\\?php", "\\?>"]
    }
}
```

Only real change was the prompt regex, which I still don't understand 100%.  Not an issue per se, but I thought it might be useful to someone.

**Comment by jcartledge** [comment]
That's cool - I'll add it to the README. Thanks!
